import Vue from 'vue';

import ButtonCustom from './Buttons/ButtonCustom.vue';
import ButtonLogOut from './Buttons/ButtonLogOut.vue';
import ButtonSwitchCompany from './Buttons/ButtonSwitchCompany.vue';
import InputLoginPanel from './Inputs/InputLoginPanel.vue';
import InputSearch from './Inputs/InputSearch.vue';
import LoginHeader from './LoginHeader/LoginHeader.vue';
import NavigationBarTop from './NavigationBar/NavigationBarTop.vue';
import NavigationBarBottom from './NavigationBar/NavigationBarBottom.vue';
import NavigationItem from './NavigationBar/NavigationItem.vue';
import InputSelect from './Inputs/InputSelect.vue';
import InputCheckBox from './Inputs/InputCheckBox.vue';
import InputAddFile from './Inputs/InputAddFile.vue';
import UserAddForm from './Forms/UserAddForm.vue';
import OfficeAddForm from './Forms/OfficeAddForm.vue';
import LevelAddForm from './Forms/LevelAddForm.vue';
import POIsAddForm from './Forms/POIsAddForm.vue';
import BeaconAddForm from './Forms/BeaconAddForm.vue';
import RequestTopicAddForm from './Forms/RequestTopicAddForm.vue';


Vue.component(ButtonCustom.name, ButtonCustom);
Vue.component(InputLoginPanel.name, InputLoginPanel);
Vue.component(InputSearch.name, InputSearch);
Vue.component(LoginHeader.name, LoginHeader);
Vue.component(ButtonLogOut.name, ButtonLogOut);
Vue.component(ButtonSwitchCompany.name, ButtonSwitchCompany);
Vue.component(NavigationBarTop.name, NavigationBarTop);
Vue.component(NavigationBarBottom.name, NavigationBarBottom);
Vue.component(NavigationItem.name, NavigationItem);
Vue.component(InputSelect.name, InputSelect);
Vue.component(InputCheckBox.name, InputCheckBox);
Vue.component(InputAddFile.name, InputAddFile);
Vue.component(UserAddForm.name, UserAddForm);
Vue.component(OfficeAddForm.name, OfficeAddForm);
Vue.component(LevelAddForm.name, LevelAddForm);
Vue.component(POIsAddForm.name, POIsAddForm);
Vue.component(BeaconAddForm.name, BeaconAddForm);
Vue.component(RequestTopicAddForm.name, RequestTopicAddForm);
